apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: resource-practicing
spec:
  containers:
  - name: nginx
    image: nginx
  - name: alma-linux
    image: almalinux
    command: ["sleep", "300"]
